<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('notification_settings')->insert([
            [
                'id' => 1,
                'type' => 'edit_email_template',
                'is_editable' => 1,
                'addon_identifier' => null,
                'user_types' => json_encode(['admin', 'user']),
                'system_notification' => json_encode(['admin' => '1', 'user' => '1']),
                'email_notification' => json_encode(['admin' => '1', 'user' => '0']),
                'subject' => json_encode(['admin' => 'New user registered', 'user' => 'Registered successfully']),
                'template' => json_encode([
                    'admin' => 'New user registered [user_name] \r\n<br>User email: <b>[user_email]</b>',
                    'user' => 'You have successfully registered with us at [system_name].'
                ]),
                'setting_title' => 'New user registration',
                'setting_sub_title' => 'Get notified when a new user signs up',
                'date_updated' => '1693215071',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-12-05 01:23:15',
            ],
            [
                'id' => 2,
                'type' => 'email_verification',
                'is_editable' => 0,
                'addon_identifier' => null,
                'user_types' => json_encode(['user']),
                'system_notification' => json_encode(['user' => '0']),
                'email_notification' => json_encode(['user' => '1']),
                'subject' => json_encode(['user' => 'Email verification code']),
                'template' => json_encode(['user' => 'You have received a email verification code. Your verification code is [email_verification_code]']),
                'setting_title' => 'Email verification',
                'setting_sub_title' => 'It is permanently enabled for student email verification.',
                'date_updated' => '1684135777',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 3,
                'type' => 'forget_password_mail',
                'is_editable' => 0,
                'addon_identifier' => null,
                'user_types' => json_encode(['user']),
                'system_notification' => json_encode(['user' => '0']),
                'email_notification' => json_encode(['user' => '1']),
                'subject' => json_encode(['user' => 'Forgot password verification code']),
                'template' => json_encode(['user' => 'You have received a email verification code. Your verification code is [system_name][verification_link][minutes]']),
                'setting_title' => 'Forgot password mail',
                'setting_sub_title' => 'It is permanently enabled for student email verification.',
                'date_updated' => '1684145383',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 4,
                'type' => 'new_device_login_confirmation',
                'is_editable' => 0,
                'addon_identifier' => null,
                'user_types' => json_encode(['user']),
                'system_notification' => json_encode(['user' => '0']),
                'email_notification' => json_encode(['user' => '1']),
                'subject' => json_encode(['user' => 'Please confirm your login']),
                'template' => json_encode(['user' => 'Have you tried logging in with a different device? Confirm using the verification code. Your verification code is [verification_code]. Remember that you will lose access to your previous device after logging in to the new device <b>[user_agent]</b>.<br> Use the verification code within [minutes] minutes']),
                'setting_title' => 'Account security alert',
                'setting_sub_title' => 'Send verification code for login from a new device',
                'date_updated' => '1684145383',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 6,
                'type' => 'course_purchase',
                'is_editable' => 1,
                'addon_identifier' => null,
                'user_types' => json_encode(['admin', 'student', 'instructor']),
                'system_notification' => json_encode(['admin' => '1', 'student' => '1', 'instructor' => '1']),
                'email_notification' => json_encode(['admin' => '0', 'student' => '0', 'instructor' => '0']),
                'subject' => json_encode(['admin' => 'A new course has been sold', 'instructor' => 'A new course has been sold', 'student' => 'You have purchased a new course']),
                'template' => json_encode([
                    'admin' => '<p>Course title: [course_title]</p><p>Student: [student_name]</p><p>Paid amount: [paid_amount]</p><p>Instructor: [instructor_name]</p>',
                    'instructor' => 'Course title: [course_title]\r\nStudent: [student_name]\r\nPaid amount: [paid_amount]',
                    'student' => 'Course title: [course_title]\r\nPaid amount: [paid_amount]\r\nInstructor: [instructor_name]'
                ]),
                'setting_title' => 'Course purchase notification',
                'setting_sub_title' => 'Stay up-to-date on student course purchases.',
                'date_updated' => '1684303456',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 7,
                'type' => 'course_completion_mail',
                'is_editable' => 1,
                'addon_identifier' => null,
                'user_types' => json_encode(['student', 'instructor']),
                'system_notification' => json_encode(['student' => '1', 'instructor' => '1']),
                'email_notification' => json_encode(['student' => '0', 'instructor' => '0']),
                'subject' => json_encode(['instructor' => 'Course completion', 'student' => 'You have completed a new course']),
                'template' => json_encode([
                    'instructor' => 'Course completed [course_title]\r\nStudent: [student_name]',
                    'student' => 'Course: [course_title]\r\nInstructor: [instructor_name]'
                ]),
                'setting_title' => 'Course completion mail',
                'setting_sub_title' => 'Stay up to date on student course completion.',
                'date_updated' => '1684303457',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 8,
                'type' => 'certificate_eligibility',
                'is_editable' => 1,
                'addon_identifier' => 'certificate',
                'user_types' => json_encode(['student', 'instructor']),
                'system_notification' => json_encode(['student' => '1', 'instructor' => '1']),
                'email_notification' => json_encode(['student' => '0', 'instructor' => '0']),
                'subject' => json_encode(['instructor' => 'Certificate eligibility', 'student' => 'certificate eligibility']),
                'template' => json_encode([
                    'instructor' => 'Course: [course_title]\r\nStudent: [student_name]\r\nCertificate link: [certificate_link]',
                    'student' => 'Course: [course_title]\r\nInstructor: [instructor_name]\r\nCertificate link: [certificate_link]'
                ]),
                'setting_title' => 'Course eligibility notification',
                'setting_sub_title' => 'Stay up to date on course certificate eligibility.',
                'date_updated' => '1684303460',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 9,
                'type' => 'offline_payment_suspended_mail',
                'is_editable' => 1,
                'addon_identifier' => 'offline_payment',
                'user_types' => json_encode(['student']),
                'system_notification' => json_encode(['student' => '1']),
                'email_notification' => json_encode(['student' => '0']),
                'subject' => json_encode(['student' => 'Your payment has been suspended']),
                'template' => json_encode(['student' => '<p>Your offline payment has been <b style=\'color: red;\'>suspended</b>!</p><p>Please provide a valid document of your payment.</p>']),
                'setting_title' => 'Offline payment suspended mail',
                'setting_sub_title' => 'If students provide fake information, notify them of the suspension',
                'date_updated' => '1684303463',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 10,
                'type' => 'bundle_purchase',
                'is_editable' => 1,
                'addon_identifier' => 'course_bundle',
                'user_types' => json_encode(['admin', 'student', 'instructor']),
                'system_notification' => json_encode(['admin' => '1', 'student' => '1', 'instructor' => '1']),
                'email_notification' => json_encode(['admin' => '0', 'student' => '0', 'instructor' => '0']),
                'subject' => json_encode(['admin' => 'A new course bundle has been sold', 'instructor' => 'A new course bundle has been sold', 'student' => 'You have purchased a new course bundle test']),
                'template' => json_encode([
                    'admin' => 'Course bundle: [bundle_title]\r\nStudent: [student_name]\r\nInstructor: [instructor_name]',
                    'instructor' => 'Course bundle: [bundle_title]\r\nStudent: [student_name]',
                    'student' => 'Course bundle: [bundle_title]\r\nInstructor: [instructor_name]'
                ]),
                'setting_title' => 'Course bundle purchase notification',
                'setting_sub_title' => 'Stay up-to-date on student course bundle purchases.',
                'date_updated' => '1684303467',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 13,
                'type' => 'add_new_user_as_affiliator',
                'is_editable' => 0,
                'addon_identifier' => 'affiliate_course',
                'user_types' => json_encode(['affiliator']),
                'system_notification' => json_encode(['affiliator' => '0']),
                'email_notification' => json_encode(['affiliator' => '1']),
                'subject' => json_encode(['affiliator' => 'Congratulation! You are assigned as an affiliator']),
                'template' => json_encode(['affiliator' => 'You are assigned as a website Affiliator.\r\nWebsite: [website_link]\r\n<br>\r\nPassword: [password]']),
                'setting_title' => 'New user added as affiliator',
                'setting_sub_title' => 'Send account information to the new user',
                'date_updated' => '1684135777',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 14,
                'type' => 'affiliator_approval_notification',
                'is_editable' => 1,
                'addon_identifier' => 'affiliate_course',
                'user_types' => json_encode(['affiliator']),
                'system_notification' => json_encode(['affiliator' => '1']),
                'email_notification' => json_encode(['affiliator' => '0']),
                'subject' => json_encode(['affiliator' => 'Congratulations! Your affiliate request has been approved']),
                'template' => json_encode(['affiliator' => 'Congratulations! Your affiliate request has been approved']),
                'setting_title' => 'Affiliate approval notification',
                'setting_sub_title' => 'Send affiliate approval mail to the user account',
                'date_updated' => '1684303472',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 15,
                'type' => 'affiliator_request_cancellation',
                'is_editable' => 1,
                'addon_identifier' => 'affiliate_course',
                'user_types' => json_encode(['affiliator']),
                'system_notification' => json_encode(['affiliator' => '1']),
                'email_notification' => json_encode(['affiliator' => '0']),
                'subject' => json_encode(['affiliator' => 'Sorry! Your request has been currently refused']),
                'template' => json_encode(['affiliator' => 'Sorry! Your request has been currently refused.']),
                'setting_title' => 'Affiliator request cancellation',
                'setting_sub_title' => 'Send mail, when you cancel the affiliation request',
                'date_updated' => '1684303473',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 16,
                'type' => 'affiliation_amount_withdrawal_request',
                'is_editable' => 1,
                'addon_identifier' => 'affiliate_course',
                'user_types' => json_encode(['admin', 'affiliator']),
                'system_notification' => json_encode(['admin' => '1', 'affiliator' => '1']),
                'email_notification' => json_encode(['admin' => '0', 'affiliator' => '0']),
                'subject' => json_encode(['admin' => 'New money withdrawal request', 'affiliator' => 'New money withdrawal request']),
                'template' => json_encode([
                    'admin' => "New money withdrawal request by [user_name] [amount]",
                    'affiliator' => "Your Withdrawal request of [amount] has been sent to authority"
                ]),
                'setting_title' => 'Affiliation money withdrawal request',
                'setting_sub_title' => 'Send mail, when the users request the withdrawal of money',
                'date_updated' => '1684303476',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 17,
                'type' => 'approval_affiliation_amount_withdrawal_request',
                'is_editable' => 1,
                'addon_identifier' => 'affiliate_course',
                'user_types' => json_encode(['affiliator']),
                'system_notification' => json_encode(['affiliator' => '1']),
                'email_notification' => json_encode(['affiliator' => '0']),
                'subject' => json_encode(['affiliator' => 'Congratulation! Your withdrawal request has been approved']),
                'template' => json_encode(['affiliator' => 'Congratulation! Your payment request has been approved.']),
                'setting_title' => 'Approval of withdrawal request of affiliation',
                'setting_sub_title' => 'Send mail, when you approved the affiliation withdrawal request',
                'date_updated' => '1684303480',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-02 11:13:07',
            ],
            [
                'id' => 18,
                'type' => 'course_gift',
                'is_editable' => 1,
                'addon_identifier' => null,
                'user_types' => json_encode(['payer', 'receiver']),
                'system_notification' => json_encode(['payer' => '1', 'receiver' => '1']),
                'email_notification' => json_encode(['payer' => '1', 'receiver' => '1']),
                'subject' => json_encode(['payer' => 'You have gifted a course', 'receiver' => 'You have received a course gift']),
                'template' => json_encode([
                    'payer' => 'You have gifted a course to [user_name] [course_title][instructor]',
                    'receiver' => 'You have received a course gift by [payer][course_title][instructor]'
                ]),
                'setting_title' => 'Course gift notification',
                'setting_sub_title' => 'Notify users after course gift',
                'date_updated' => '1691818623',
                'created_at' => '2023-11-02 11:13:07',
                'updated_at' => '2023-11-06 05:02:28',
            ],
        ]);
    }
}
